django/project/diary/urls.py
from django.urls import path
from .import views

app_name = 'diary'

urlpatterns = [
    path('', views.index, name = 'index'), #/diary
    path('add/', views.add, name = 'add'), #/dairy/add

]
heyhey

django/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls')),
]

django/project/diary/models.py
from django.db import models
from django.utils import timezone #djangoでは、fatetime.nowのかわりに、timezone.nowで現在日付・時刻を取得する

# Create your models here.

class Day(models.Model):
    title = models.CharField('タイトル', max_length = 200)
    text = models.TextField('本文')
    date = models.DateTimeField('日付', default = timezone.now)

django/project/diary/forms.py
from django import forms
from .models import Day


class DayCreateForm(forms.ModelForm):

    class Meta:
        model = Day
        fields = '__all__' #('title','text','date')

django/project/diary/views.py
from django.shortcuts import render,redirect
from .forms import DayCreateForm
from .models import Day


def index(request):
    context = {
        'day_list': Day.objects.all(),       
    }
    return render(request,'diary/day_list.html',context)


def add(request):
    #送信内容を基にフォームを作る。POSTじゃなければ、空のフォーム
    form = DayCreateForm(request.POST or None)

    #method=POST、つまり送信ボタン押下時、入力内容が問題なければ
    if request.method == 'POST' and form.is_valid():
        form.save()
        return redirect('diary:index')
    
    #通常時のページアクセスや、入力内容に誤りがあればまたページを表示
    context = {
        'form': form
    }
    return render(request,'diary/day_form.html',context)

django/project/diary/templates/diary/base.html
<!doctype html>
<html lang="ja">
  <head>
<<<<<<< HEAD
    <title>bbbbbbbbbbbbbbbb</title>
=======
    <title>aiueooooooooooooooo</title>
>>>>>>> branch_a
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>
  <body>
    <div class ="container">
      <nav class="nav">
        <a class="nav-link" href="{% url 'diary:index' %}">一覧</a>
        <a class="nav-link" href="{% url 'diary:add' %}">追加</a>
      </nav>
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% block extrajs %}{% endblock %}
  </body>
</html>

django/project/diary/templates/diary/day_form.html
{% extends 'diary/base.html' %}

{% block content %}
<form action = ""method = "POST">
    <table class = "table">
        <tr>
            <th>タイトル</th>
            <td>{{ form.title }}</td>
        </tr>
        <tr>
            <th>本文</th>
            <td>{{ form.text }}</td>
        </tr>
        <tr>
            <th>日付</th>
            <td>{{ form.date }}</td>
        </tr>
    </table>
    <button type = "submit" class = "btn btn-primary">送信</button>
    {% csrf_token %}
</form>
{% endblock %}

django/project/diary/templates/diary/day_list.html
{% extends 'diary/base.html' %}

{% block content %}
<h1>日記一覧</h1>
<table class = "table">
    <thead>
        <tr>
            <th>タイトル</th>
            <th>日付</th>
        </tr>
    </thead>
    <tbody>
        {% for day in day_list %}
        <tr>
            <td>{{ day.title }}</td>
            <td>{{ day.date }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}